// Topic content is rendered directly; terms contain only extra search aliases not already supplied by title, summary, or body.
export const GUIDE_TOPICS = [
  {
    id: "getting-started",
    title: "Getting started",
    summary: "You do not need to set up every feature. Start with the basics, make sure Home Assistant access is correct, then add extra features only when you need them.",
    terms: "setup first steps beginner basics save draft exposed entities assist provider",
    body: [
      {type: "p", text: "Extended OpenAI can work well with only a small amount of setup. Features such as memory, reference information, custom actions, voice identity and privacy controls are optional extras that you can add later."},
      {type: "heading", text: "A good first setup"},
      {type: "steps", items: ["Choose the conversation agent you want to set up using the selector at the top of the page. Each agent has its own model, instructions, features and saved data.","Go to Assistant → Basics and choose the AI model you want to use. For most people, API format can stay on Auto and the other default settings are a good place to start.","Check which Home Assistant entities are exposed to Assist. Exposure determines which normal Home Assistant entities are available to the assistant, but control also requires permission from the Home Assistant user making the request and can be restricted further by Extended OpenAI policies such as Guest Mode.","Try using the assistant before turning on lots of extra features. Add persistent memory, Knowledge sources or custom Function Tools only when you have a reason to use them.","If you want to see what information will be sent to the model, use Preview effective request. If something is not working, Diagnostics can help you test the connection and find problems."]},
      {type: "note", title: "You can keep it simple", text: "You do not need to understand or change every setting. For a basic working assistant, you mainly need a model, useful instructions and the Home Assistant entities you already expose to Assist."},
      {type: "p", text: "Settings pages share a draft while you move between related sections. Changes are not saved automatically, so remember to press Save when you are finished."},
    ],
    action: {label: "Configure the assistant", page: "assistant", section: "basics"},
  },
  {
    id: "models",
    title: "Choosing a model and provider",
    summary: "The provider is the AI service you connect to, while the model is the specific AI model that answers you. Most users can leave API format on Auto.",
    terms: "model provider api responses chat completions reasoning effort service tier temperature top p tokens",
    body: [
      {type: "p", text: "The provider is the online AI service that Home Assistant connects to. The model is the particular AI model you want that service to use. One provider may offer several models, and different models may support different features."},
      {type: "heading", text: "The settings that matter most"},
      {type: "list", items: ["Chat model chooses which AI model the provider should use.","API format chooses the type of request Extended OpenAI sends to the provider. Auto is recommended for most users because the integration can choose the appropriate supported format for you.","Maximum response length limits how much text the model can return in a single answer.","Maximum tool calls limits how many actions or tools the model can use during one request, helping prevent it from repeatedly calling tools without a sensible end."]},
      {type: "p", text: "Some models have extra settings, such as reasoning effort or service tier. These only work if your chosen model and provider support them. Higher reasoning effort can improve answers to more difficult questions, but it may also make replies slower and use more tokens."},
      {type: "note", title: "Using a custom provider", text: "A service that describes itself as “OpenAI-compatible” may still support only some OpenAI features. If a custom provider has trouble with the Responses API, tools or advanced model settings, check which API format that provider recommends rather than assuming every option will work."},
      {type: "p", text: "If you are unsure what to choose, select your model, leave API format on Auto and keep the advanced response settings at their defaults. You can change them later if you find a specific reason to."},
    ],
    action: {label: "Open model settings", page: "assistant", section: "model-responses"},
  },
  {
    id: "model-data",
    title: "Model data and capability updates",
    summary: "Model data tells Extended OpenAI which response controls and API features a model supports, and it can be refreshed separately from integration releases.",
    terms: "model data catalog catalogue capabilities refresh update bundled fallback reasoning temperature service tier",
    body: [
      {type: "p", text: "Extended OpenAI keeps model capability information separately from your agent configuration. This lets the management UI show controls such as reasoning effort, temperature, service tier, and compatible API modes only where they are expected to work."},
      {type: "p", text: "You can refresh the model data without updating or reloading the integration. Loaded agents use refreshed capability data immediately. If the remote update is unavailable or unsuitable, you can return to the model data bundled with the installed integration."},
      {type: "note", title: "Model data is guidance, not a provider guarantee", text: "Custom or OpenAI-compatible providers may implement a model differently from the provider the catalogue describes. If a provider rejects an option, use the settings that provider actually supports."},
    ],
    action: {label: "Open diagnostics", page: "usage-maintenance", section: "diagnostics"},
  },
  {
    id: "continuity",
    title: "Conversation continuity",
    summary: "Conversation continuity lets the assistant remember the recent discussion so follow-up questions can make sense.",
    terms: "conversation continuity follow up timeout recent context device user sessions resume history",
    body: [
      {type: "p", text: "Normally, a new Assist request may be treated as a completely new conversation. Conversation continuity keeps the recent discussion available, so a follow-up such as “what about tomorrow?” can still refer to what you were just talking about."},
      {type: "heading", text: "Ways a conversation can continue"},
      {type: "list", items: ["Use Home Assistant sessions follows Home Assistant's normal conversation and session behaviour.","Remember by voice device lets a voice device continue its recent conversation even after the immediate Assist session has ended.","Remember by user across devices lets the same identified user continue a recent conversation from a different device."]},
      {type: "p", text: "When Extended OpenAI is managing continuity itself, the conversation timeout controls how long a conversation can sit unused before the next request starts a new one. A shorter timeout reduces the chance of an old conversation being continued by mistake. A longer timeout makes it easier to return to a discussion later. Live continuity and its conversation-scoped Function Group and Request Rule state are intentionally kept in memory, so a Home Assistant restart also starts fresh. You can explicitly ask the assistant to start a fresh conversation; that reset takes effect after the current reply and clears only live context, loaded groups, conversation routing overrides and the conversation's automatic memory selection. It does not delete Persistent Memory, Temporary Memory, Knowledge Library sources or archived conversation history."},
      {type: "note", title: "This is not long-term memory", text: "Conversation continuity keeps the recent discussion together. Persistent memory stores reusable facts for later, while the conversation archive stores old conversations that you can review or search. These are separate features."},
      {type: "p", text: "Very long conversations can eventually become too large to keep sending to the model. Context-management settings decide what happens at that point: the integration can keep the newest complete turns, remove older context, or summarize older parts of the conversation once the configured limit is reached."},
    ],
    action: {label: "Configure continuity", page: "assistant", section: "conversation"},
  },
  {
    id: "context-management",
    title: "Context management for long conversations",
    summary: "Context management reduces old conversation history when a conversation grows beyond the configured input-token threshold.",
    terms: "context management trim history threshold keep recent clear summarize summary long conversation tokens",
    body: [
      {type: "p", text: "Long conversations can eventually become too large or expensive to keep sending in full. The Trim history after setting defines the input-token threshold at which Extended OpenAI reduces older conversation history."},
      {type: "list", items: ["Keep recent messages removes the oldest complete user turns while preserving the newest useful context and complete tool call/result units.","Clear all messages removes the retained conversation history when the threshold is reached.","Summarize older messages makes one bounded model request after the current reply to condense older context. The next turn waits for that summary if it is still pending, and a failed summary falls back to keeping recent messages."]},
      {type: "note", title: "This does not delete saved memory", text: "Context trimming changes the live conversation history sent to the model. It does not delete Persistent Memory, Temporary Memory, Knowledge Library sources, or archived conversations."},
    ],
    action: {label: "Configure context management", page: "assistant", section: "conversation"},
  },
  {
    id: "memory",
    title: "What the assistant can remember",
    summary: "Extended OpenAI has several different kinds of memory and history. Each is intended for a different job.",
    terms: "memory comparison context temporary persistent archive knowledge remember data retention difference",
    body: [
      {type: "p", text: "Several features can make the assistant seem as though it “remembers” something, but they work in different ways. Using the right one keeps requests smaller and makes it clearer what information is being stored."},
      {type: "list", items: ["Conversation context keeps the recent back-and-forth so normal follow-up questions make sense.","Temporary memory stores useful facts that should automatically stop being active at a particular expiry time.","Persistent memory stores longer-lasting facts or preferences that may be useful in future conversations.","Conversation archive stores previous discussions so you can review them and, if enabled, let the assistant search them later.","Knowledge Library stores larger reference material that the assistant can search when it needs information from it."]},
      {type: "note", title: "Use the simplest option that fits", text: "If a fact only matters until tomorrow, temporary memory is usually better than permanent memory. A long manual belongs in Knowledge rather than memory. A normal follow-up question usually only needs conversation continuity."},
      {type: "p", text: "The comparison table at the bottom of this Guide shows these five features side by side."},
    ],
    action: {label: "Manage memories", page: "data-memory", section: "memories"},
  },
  {
    id: "persistent-memory",
    title: "Persistent memory",
    summary: "Persistent memory stores useful facts and preferences so you do not have to explain them again in future conversations.",
    terms: "persistent long term memory manual automatic lexical semantic embeddings retrieve shared personal remember preference fact",
    body: [
      {type: "p", text: "Persistent memory is best for information that is likely to remain useful over time, such as preferences, stable facts, recurring personal context or anything else you would otherwise need to repeat regularly."},
      {type: "heading", text: "Choose how memories are saved"},
      {type: "list", items: ["Off means persistent memories are neither saved nor retrieved for this agent.","Manual means a memory is saved only when you specifically ask the assistant to remember something.","Automatic also allows the assistant to save stable and useful information by itself, following the integration's memory rules."]},
      {type: "p", text: "Automatically include memories controls how many relevant memories may be added when a new conversation begins. That selected set is then reused for the conversation rather than choosing memories again after every message. Set this to 0 if you prefer memories to be used only when the assistant deliberately searches for them using its memory tools."},
      {type: "p", text: "For finding relevant memories, lightweight lexical retrieval looks for matching words and related text locally. Hybrid semantic retrieval can also use embeddings, which are a way of finding information with a similar meaning even when different words were used. If embeddings are not available, Extended OpenAI falls back to the local word-based method."},
      {type: "note", title: "What makes a good persistent memory?", text: "Save information that is likely to be useful beyond the current conversation. Short-term plans, one-off status updates and facts with a clear expiry time are usually better suited to temporary memory."},
      {type: "p", text: "You can review and delete saved memories at any time under Data & Memory → Memories. You do not have to rely on the AI model to tell you what it has stored."},
    ],
    action: {label: "Manage persistent memory", page: "data-memory", section: "memories"},
  },
  {
    id: "temporary-memory",
    title: "Temporary memory",
    summary: "Temporary memory keeps short-lived information available for a limited time and then lets it expire automatically.",
    terms: "temporary short term memory expiry expiring reminder current visitor package until tomorrow",
    body: [
      {type: "p", text: "Temporary memory is useful when the assistant should know something for a while, but the information should not become a permanent fact."},
      {type: "list", items: ["“We have a guest staying until Sunday.”","“The car is in the garage until tomorrow afternoon.”","“For the next week, use the temporary work address.”"]},
      {type: "p", text: "While the memory is still active, the assistant can use it when it is relevant. After the expiry time passes, it is no longer treated as active information."},
      {type: "note", title: "An expiry time is not a reminder", text: "Temporary memory does not schedule a notification or cause the assistant to contact you when the expiry time arrives. The expiry only decides how long the information remains available as memory."},
      {type: "p", text: "Use persistent memory when information should remain until you change or delete it. Use conversation continuity when the information only needs to last for the current discussion."},
    ],
    action: {label: "View temporary memories", page: "data-memory", section: "memories"},
  },
  {
    id: "archive",
    title: "Conversation archive",
    summary: "The archive stores previous conversations so you can review or search them later. It is separate from the recent context used for an active conversation.",
    terms: "archive conversation history retained search retention sessions past discussions privacy delete",
    body: [
      {type: "p", text: "Conversation continuity answers “what were we just talking about?”. The conversation archive answers “what did we discuss in the past?”. It stores conversation records for the retention period you choose."},
      {type: "p", text: "Under Data & Memory → Conversation history, you can browse saved conversations, search them, open individual sessions and delete them. Administrators can also see recent active continuity sessions and choose to make a session start fresh the next time it is used."},
      {type: "note", title: "Your whole archive is not sent with every request", text: "Archived conversations are stored separately. If assistant archive search is enabled, the assistant can search for relevant past discussions when needed instead of placing every old conversation into every model request."},
      {type: "p", text: "Retention settings decide how long archived conversations are kept. If you do not need searchable conversation history, leaving the archive disabled reduces the amount of conversation data stored."},
    ],
    action: {label: "Open conversation history", page: "data-memory", section: "conversations"},
  },
  {
    id: "knowledge",
    title: "Knowledge Library",
    summary: "Knowledge Library stores larger reference material that the assistant can search when needed instead of sending all of it with every request.",
    terms: "knowledge library source document manual reference search retrieval article text local excerpts",
    body: [
      {type: "p", text: "Use Knowledge Library for information that is too large or detailed to work well as a few memories. Examples include manuals, policies, household notes, project documentation, procedures and other reference material that you maintain."},
      {type: "p", text: "Knowledge sources are stored with the agent and indexed locally so they can be searched. Each source can also be disabled independently. A disabled source stays stored and editable, but it is removed from the assistant's Knowledge catalogue, search index and retrieval until you enable it again. When Knowledge is enabled, the assistant can search the available sources, see which sources match and retrieve only the useful part of a source. The entire library is not added to every model request."},
      {type: "note", title: "Knowledge is different from memory", text: "Memory is better for small facts about people, preferences or ongoing context. Knowledge is better for larger reference material that the assistant should look up when a question requires it."},
      {type: "p", text: "Turning the Knowledge capability off does not delete your saved sources. It simply prevents the assistant from using the Knowledge tools until you enable them again."},
      {type: "p", text: "If you use Guest Mode, you can separately choose whether guests may use all available Knowledge sources, no Knowledge sources, or only specific sources that you select. Guest permissions can only restrict availability further; they cannot make a disabled source available."},
    ],
    action: {label: "Open Knowledge Library", page: "data-memory", section: "knowledge"},
  },
  {
    id: "functions",
    title: "Function Tools and Function Groups",
    summary: "Function Tools give the assistant extra actions beyond normal Home Assistant control. Function Groups help keep large collections of tools efficient.",
    terms: "function tools groups yaml actions capabilities built in on demand loading token schemas enabled disabled",
    body: [
      {type: "p", text: "You do not need to create a Function Tool just to control normal Home Assistant devices. The assistant can already work with the Home Assistant entities and actions that are exposed through Assist."},
      {type: "p", text: "Create a Function Tool when you want to give the AI an extra capability or a specially defined action. Function Tools are configured using YAML, a structured text format commonly used by Home Assistant. Extended OpenAI checks the configuration before saving it. If a tool is disabled, its setup is kept, but the model cannot see or use it."},
      {type: "heading", text: "What Function Groups are for"},
      {type: "p", text: "Every Function Tool needs instructions that explain it to the model. If you have many tools, sending all of those instructions with every request can use unnecessary input tokens. Function Groups let you decide which tool instructions are always sent and which are loaded only when needed. Each group can also be disabled independently: its member Function Tool settings are kept, but none of those tools are available to the model until the group is enabled again."},
      {type: "list", items: ["Functions that are not in a group are always available, so their full instructions are sent with requests.","A group set to Always available works the same way: its functions are ready for immediate use.","A group set to Load when needed initially sends only a short description of the group. If the model decides it needs those functions, it can then load the full definitions."]},
      {type: "note", title: "The trade-off", text: "Load when needed can reduce repeated input-token use when you have many tools. However, the first time the assistant needs a group during a request, it may require one extra exchange with the model to load it."},
      {type: "p", text: "Disabling a Function Group does not disable its member Function Tools individually. Re-enabling the group restores only the members that are individually enabled. Deleting a Function Group is different: it does not delete the functions, but they become ungrouped and therefore return to the normal always-available collection unless you place them in another group. If an agent has Skills selected, Extended OpenAI also protects the built-in load_skill tool from becoming unavailable through tool state, group state, or a zero tool-call limit."},
      {type: "heading", text: "Delayed Function Tool execution"},
      {type: "p", text: "Configured Function Tools can request delayed execution for future device actions. Pending delayed calls are persisted across Home Assistant restarts. When a call becomes due, Extended OpenAI rechecks the current configuration, requesting user's Home Assistant permissions, and applicable authorization policy before execution. A call that had already crossed the execution boundary before an unexpected process stop is not replayed automatically."},
    ],
    action: {label: "Manage functions", page: "capabilities", section: "functions"},
  },
  {
    id: "quiet-hours",
    title: "Quiet Hours for Assist satellites",
    summary: "Quiet Hours can lower Assist satellite speaker volume and optionally suppress wake-word sounds during a daily time window.",
    terms: "quiet hours night satellite speaker volume wake word sound chime schedule automation binary sensor",
    body: [
      {type: "p", text: "Quiet Hours is a global daily schedule for Assist satellites. During the configured period, it can cap each satellite's speaker volume and, where a compatible switch is available, turn the wake-word chime off or on."},
      {type: "list", items: ["Quiet Hours only turns a louder speaker down to the configured maximum; it does not raise a quieter speaker.","Extended OpenAI tries to discover satellite speaker and wake-word entities automatically, with manual overrides available when discovery is wrong or incomplete.","A read-only Quiet Hours entity stays on for the scheduled period, so normal Home Assistant automations can use the same schedule for LEDs or other device-specific behaviour."]},
      {type: "note", title: "Your own changes are preserved", text: "Extended OpenAI remembers the volume it changed and restores it only when Quiet Hours still owns that value. If you or another automation changes the speaker while Quiet Hours is active, that newer value is left alone."},
      {type: "p", text: "If Home Assistant starts or restarts while the current time is already inside the saved Quiet Hours period, the schedule catches up and applies the active policy. The enable_quiet_hours and disable_quiet_hours actions can also turn the saved schedule on or off."},
    ],
    action: {label: "Configure Quiet Hours", page: "capabilities", section: "quiet-hours"},
  },
  {
    id: "request-rules",
    title: "Request Rules",
    summary: "Request Rules let you handle predictable phrases deterministically with local actions, Function Tools, conditions, AI routing, and reusable shared rules.",
    terms: "request rules local command sentence pattern optional choice variable capture captured value condition only when group priority order continue matching rule sharing import export fuzzy routing model action automation voice shortcut",
    body: [
      {type: "p", text: "Request Rules check text before it is sent to the AI provider. They only apply after Home Assistant has already chosen this Extended OpenAI conversation agent to handle the request."},
      {type: "p", text: "A local rule can run Home Assistant actions or enabled Function Tools without an AI call. A routing rule can change the model or reasoning used for a request or conversation. Local rules can also run first and then continue to the AI when that is what you want."},
      {type: "heading", text: "Matching and priority"},
      {type: "list", items: ["Rules have one global priority order. In the All rules view, the order shown is the order checked. Groups only help organise and filter rules; they do not change priority.","By default, the first eligible matching rule handles the request. An advanced rule can enable Continue matching after this rule so later matching rules may also run. AI handoff, an error, or a denied action stops further matching.","Only when conditions use Home Assistant's native condition editor. Text matching happens first; a false condition skips that rule, while an evaluation error stops safely.","Equals is the narrowest text match. Starts with, Ends with and Contains are broader. Fuzzy matching is considered only after strict candidates are exhausted."]},
      {type: "heading", text: "ExtendedOpenAI sentence patterns"},
      {type: "p", text: "For flexible command shapes, use ExtendedOpenAI sentence patterns. This is a small pattern language owned by ExtendedOpenAI rather than Home Assistant/Hassil grammar. It supports optional text such as [please], choices such as (turn|switch), free-text captures such as {question}, constrained captures such as {room=kitchen|bedroom}, and numeric ranges such as {level=0..100}."},
      {type: "p", text: "Captured values can be reused in supported action or Function Tool inputs and in local responses. If Continue to AI is enabled, AI input can be the Original request or one captured value that is guaranteed to exist for every trigger variant."},
      {type: "heading", text: "Actions and Function results"},
      {type: "p", text: "The editor uses Home Assistant's normal action and condition selectors where possible. A local rule can also call an enabled ExtendedOpenAI Function Tool directly. Give a Function result an alias when later steps or the local response need to reference fields from that result. Function results stay inside that rule and are not automatically sent to the AI provider."},
      {type: "p", text: "Native script results take precedence: failures and false top-level conditions use the failure response; Set conversation response overrides the generic success response; a successful Stop consumes the request locally; Continue to AI runs only after normal completion without a final response or stop. Script variables and response_variable stay within the action sequence and are not automatically available in the separate success response."},
      {type: "heading", text: "Testing and sharing"},
      {type: "p", text: "Match Preview is safe: it shows which rules would match, captured values, and where checking would stop without running actions, Function Tools, or the AI provider. Live Test uses the real processing path and can perform actions, so use it deliberately."},
      {type: "p", text: "Rule Sharing at the bottom of the page can export all rules, one group, or selected rules. Imports are reviewed first, appended after existing rules in their shared relative order, and start disabled. Newly created rules start enabled; toggle them on the Request Rules list. Rule packs do not include Function Tool definitions, credentials, or agent-wide wording alternatives."},
      {type: "note", title: "Request Rule or normal Home Assistant automation?", text: "Use a Request Rule when the phrase belongs specifically to this Extended OpenAI agent, should avoid an AI call, or should change AI routing. Use a normal Home Assistant sentence-trigger automation when the command should work independently of Extended OpenAI or needs normal automation ownership and behaviour."},
      {type: "heading", text: "Safety"},
      {type: "p", text: "Guest Mode and Home Assistant permissions are still enforced. Use narrow matching for sensitive actions such as locks, alarms, or garage doors. Request Rules, their groups, priority order, and matching settings are preserved by the agent's full backup."},
    ],
    action: {label: "Manage Request Rules", page: "capabilities", section: "request-rules"},
  },
  {
    id: "local-handling",
    title: "Local handling: Home Assistant before AI",
    summary: "Use Home Assistant's fast built-in commands after Request Rules, while keeping selected command types available to Function Tools or AI.",
    terms: "local handling home assistant intents built in commands no ai request prefer local handling delayed command timer request rules exceptions",
    body: [
      {type: "p", text: "Local handling is an optional shortcut for commands that Home Assistant already understands on its own. It can make simple requests faster and avoid an unnecessary AI request, without replacing the AI for more flexible or complicated language."},
      {type: "heading", text: "What happens when you speak"},
      {type: "steps", items: ["Request Rules get the first chance to handle or route the request.","If no Request Rule matched, Extended OpenAI can ask Home Assistant whether the request is one of its built-in commands.","If Home Assistant has a clear local match, it handles the command and returns its normal response without calling the AI provider.","If Home Assistant does not have a suitable match, the request continues through Extended OpenAI and the AI model as normal."]},
      {type: "p", text: "Typical local matches include straightforward requests such as turning devices on or off, checking a device state, asking for the current time or date, and managing timers. The exact list comes from the Home Assistant version you are running, so newly added Home Assistant command types can appear automatically."},
      {type: "heading", text: "Choose what should continue to AI"},
      {type: "p", text: "The Local handling settings show the command types Home Assistant currently provides. Select any item under Send these command types to AI if you want that kind of request to skip the local shortcut. Delayed device commands are included in this same list. Friendly names are shown first; the technical Hass... name is included only as a reference."},
      {type: "note", title: "Delayed device commands stay in the same list", text: "Home Assistant uses its timer command for both ordinary timers and commands such as “turn off the lights in 20 minutes”. Choose Delayed device commands in the same exception list to send those future device actions to your AI or Function Tool path while normal requests such as “set a 20 minute timer” can still be handled locally."},
      {type: "heading", text: "Check your Assist pipeline too"},
      {type: "p", text: "Home Assistant Assist has its own Prefer local handling option. If that is enabled on a pipeline using this agent, Home Assistant may complete a command before it ever reaches Extended OpenAI. The settings page warns you about affected pipelines. Turn Home Assistant's pipeline option off if you want Extended OpenAI to control the order and apply its command-type exceptions."},
      {type: "note", title: "Guest Mode keeps its existing safeguards", text: "When Guest Mode is active, this shortcut is deliberately skipped. Guest requests continue through the existing Extended OpenAI policy checks instead of bypassing them through Home Assistant's general local intent path."},
      {type: "p", text: "Leave local handling off if you prefer every non-Request-Rule command to follow the normal Extended OpenAI path. Turning it on does not stop you using AI for anything Home Assistant cannot match locally."},
    ],
    action: {label: "Configure local handling", page: "capabilities", section: "home-assistant"},
  },
  {
    id: "broadcast",
    title: "Broadcast spoken messages around the home",
    summary: "Broadcast sends one-way spoken messages to selected Assist satellites or the whole home, with busy satellites queued until they are free.",
    terms: "broadcast announce tell message satellite room area floor label whole home speaker queue alias one way",
    body: [
      {type: "p", text: "Broadcast is an optional one-way messaging feature. Enable it from the Extended OpenAI Overview, then you can type a message there or send one through voice, a Function Tool, or the Home Assistant Broadcast action."},
      {type: "heading", text: "Choose where the message goes"},
      {type: "list", items: ["Select one or more Assist satellites directly from the Overview.","Use an Assist satellite, device, area, floor, or label name in a voice or AI request.","Choose Whole home to send to every announcement-capable Assist satellite except the satellite that originated the request."]},
      {type: "p", text: "Local destination matching also checks Home Assistant aliases when they are available. For example, an area called Kitchen can also be addressed by an alias you have given that area."},
      {type: "note", title: "Broadcast destinations do not need to be exposed to Assist", text: "The Assist Satellite entities themselves do not need to be exposed to Assist. Extended OpenAI discovers announcement-capable Assist satellites directly from Home Assistant and sends the announcement to them itself."},
      {type: "heading", text: "Voice phrases that can stay local"},
      {type: "p", text: "When Extended OpenAI local handling is enabled, clear targeted wording can be resolved without an AI request. Examples include “Broadcast to kitchen that dinner is ready”, “Tell bedroom I'll be up in five”, and “Announce to upstairs saying the dog needs to go out”."},
      {type: "p", text: "If wording clearly looks like a targeted Broadcast request but the destination cannot be resolved, Extended OpenAI prevents Home Assistant's broad whole-home Broadcast intent from swallowing the request. The request can then continue to the normal AI path instead of accidentally announcing the destination words everywhere."},
      {type: "heading", text: "Busy satellites are not deliberately interrupted"},
      {type: "p", text: "If a destination satellite is listening, processing, or speaking, the message waits in that satellite's queue. Each destination is handled independently, so an idle room can receive the message while another room waits. Queued messages expire after a bounded wait rather than remaining pending forever."},
      {type: "note", title: "One-way by design", text: "This release does not add reply threads, a live two-way conversation, or recorded-voice Broadcast. Those are deliberately outside the current feature."},
    ],
    action: {label: "Open Broadcast", page: "overview", section: ""},
  },
  {
    id: "guest-mode",
    title: "Guest Mode",
    summary: "Guest Mode gives visitors a restricted version of the assistant so they do not automatically receive the owner's access, memories or conversation history.",
    terms: "guest visitors privacy exclusions labels areas domains entities knowledge functions shared memory schedule control restrictions",
    body: [
      {type: "p", text: "Guest Mode is designed for homes where another person may speak to or use the same assistant. Its restrictions are enforced by Extended OpenAI itself, rather than depending only on instructions that ask the AI model not to do certain things."},
      {type: "heading", text: "Choose which Home Assistant devices guests can access"},
      {type: "p", text: "Guests begin with the Home Assistant entities that are normally available to the assistant. You can then block anything they should not be able to use by Home Assistant label, area, domain or individual entity. If an entity matches any one of your exclusions, it is unavailable to the guest."},
      {type: "note", title: "Labels are often the easiest option", text: "For example, you could create a Home Assistant label called “Guest restricted” or “Private” and apply it to sensitive locks, cameras, trackers or other entities. Excluding that label in Guest Mode means the guest restrictions automatically follow the way you organise those entities in Home Assistant."},
      {type: "p", text: "Normally, if a guest is not allowed to read an entity, they are also not allowed to control it. Advanced options let you add extra control-only restrictions if you want an entity to be visible to guests but not controllable."},
      {type: "heading", text: "Knowledge, custom functions and memory"},
      {type: "list", items: ["Knowledge can be Off, On, or Custom. Custom lets you choose exactly which Knowledge sources guests may use.","Custom functions can be Off, On, or Custom. Custom lets you choose exactly which functions or Function Groups guests may use.","Shared household memory can be Off, Read only, or Read & write.","Personal memory and the owner's conversation archive are never available while Guest Mode is active."]},
      {type: "p", text: "Choosing On for Knowledge or custom functions means eligible sources or functions that you add in the future are also allowed automatically. Choose Custom if you want a fixed list that changes only when you edit it yourself."},
      {type: "heading", text: "Starting and ending Guest Mode"},
      {type: "p", text: "Guest Mode can start immediately or at a scheduled time. You can give it an end time or leave it active until you turn it off."},
      {type: "p", text: "The assistant can enable or extend Guest Mode, but cannot shorten or disable it. Administrators and Home Assistant automations can change or end Guest Mode."},
      {type: "p", text: "Guest conversations and owner conversations are kept separate. Turning on Guest Mode does not give a visitor the owner's recent conversation context, and turning Guest Mode off does not continue the visitor's conversation as though it belonged to the owner."},
    ],
    action: {label: "Configure Guest Mode", page: "capabilities", section: "guest-mode"},
  },
  {
    id: "voice",
    title: "Voice assistants and multiple users",
    summary: "If several people use voice devices, you can control whose conversation and saved personal data each voice request is allowed to use.",
    terms: "voice satellite device user mapping household identity scope default user unmapped continuity privacy",
    body: [
      {type: "p", text: "A request typed into Home Assistant normally comes from a known logged-in user. Voice devices can be less clear. A kitchen satellite might be used by everyone, while a phone or bedroom satellite may effectively belong to one person."},
      {type: "p", text: "Voice scope settings decide whose saved data a voice request is allowed to use. Depending on your setup, an unmapped voice request can avoid personal data entirely, use shared household data, use a default user that you choose, or use a device-to-user mapping."},
      {type: "note", title: "Identity and conversation continuity are different", text: "Voice scope answers “whose memory and saved data may this request use?”. Conversation continuity answers “which recent conversation should this request continue?”. If you use shared voice devices, think about both settings."},
      {type: "p", text: "Device-to-user mappings work well for voice devices that reliably belong to one person. For a genuinely shared satellite, shared data or no personal retention may be safer than treating every speaker as the same person."},
      {type: "p", text: "If you change your voice-device mappings, also check what happens to devices that are not mapped. A new or renamed satellite should not unexpectedly start using someone's personal saved data just because no mapping exists for it yet."},
      {type: "note", title: "How a voice device is identified", text: "When Home Assistant provides a stable device ID, Extended OpenAI uses it to identify which voice device made the request. If that is unavailable, satellite information can be used as a fallback. The mapping decides whose retained data should be used; it never gives that person extra Home Assistant permissions."},
    ],
    action: {label: "Configure voice identity", page: "assistant", section: "voice"},
  },
  {
    id: "speech-processing",
    title: "Speech cleanup for TTS",
    summary: "Speech processing removes text that is useful on screen but awkward when spoken, while keeping the original assistant response for logs and conversation history.",
    terms: "speech tts markdown urls links citations formatting regex replacements progressive streaming cleanup spoken output",
    body: [
      {type: "p", text: "Speech processing creates a speech-safe version of the assistant response for TTS. It can remove Markdown links, formatting, citations and bare URLs so they are not read aloud, while the original provider response remains available to ChatLog, conversation history and archives."},
      {type: "p", text: "The built-in cleanup can work progressively while a response is streaming, including when Markdown or URLs are split across provider chunks. This allows spoken output to start before the full answer has finished."},
      {type: "note", title: "Custom replacements wait for the completed response", text: "Custom regular-expression replacements run only after the response is complete, so enabling any custom replacement disables progressive TTS for that response. If a replacement fails or takes too long, Extended OpenAI simply uses the speech text from before the custom replacements instead of speaking a partly modified result."},
    ],
    action: {label: "Configure speech", page: "assistant", section: "speech"},
  },
  {
    id: "privacy",
    title: "Privacy and security",
    summary: "Privacy is controlled in several layers: Home Assistant access, what is sent to the model, what is stored, extra tools, Guest Mode and retention settings.",
    terms: "privacy security provider data sent local context exposed entities prompt backup guest retention memory knowledge archive tools",
    body: [
      {type: "p", text: "There is no single privacy switch because different settings control different kinds of information and access. It is easier to think of privacy in Extended OpenAI as several separate layers."},
      {type: "heading", text: "What the assistant can access"},
      {type: "steps", items: ["Home Assistant exposure decides which normal Home Assistant entities are available to Assist. It does not grant control by itself: model-driven actions also use the requesting Home Assistant user's permissions, with Extended OpenAI policies able to restrict access further.","Prompt and context settings decide which instructions and live Home Assistant information are prepared for model requests.","Memory, Knowledge and conversation archive decide which information is stored and may be retrieved again later.","Function Tools and hosted capabilities decide which extra actions or outside information the model is allowed to use.","Guest Mode places an additional, stricter visitor policy on top of your normal assistant setup.","Retention and deletion settings decide how long locally stored conversation history and detailed usage information are kept."]},
      {type: "note", title: "Stored locally does not always mean it will never be sent", text: "Memory, Knowledge and archived conversations can remain stored locally until they are needed. If the assistant retrieves some of that information to answer a question, the relevant part may then be included in a model request or returned as the result of a tool."},
      {type: "p", text: "Preview effective request lets you inspect the basic request that Extended OpenAI assembles locally for a new message, including instructions, Home Assistant context and tool definitions. It cannot show every part of provider-side handling or information that can only be decided after a future real user message is received."},
      {type: "p", text: "Full backups can contain private instructions, memories, Knowledge sources, archived conversations and usage information. Treat backup files as sensitive. Provider API credentials are kept separately and are not included in those backups."},
      {type: "p", text: "For an assistant used by several people, pay particular attention to voice identity, Guest Mode and which Home Assistant entities are exposed. These create more reliable privacy boundaries than simply putting an instruction in the prompt asking the AI model not to mention something."},
      {type: "note", title: "The most restrictive applicable policy wins", text: "Assist exposure, Home Assistant user permissions, Guest Mode, Request Rules and Function Tool policy are separate layers. Being exposed or visible does not override a user's lack of CONTROL permission, and an Extended OpenAI restriction cannot be bypassed by another more permissive layer."},
    ],
    action: {label: "Review Home Assistant access", page: "capabilities", section: "home-assistant"},
  },
  {
    id: "usage",
    title: "Usage, maintenance and troubleshooting",
    summary: "The maintenance pages help you understand token use, test the provider, inspect recent requests, manage retention and create private backups.",
    terms: "usage troubleshooting diagnostics tokens cached uncached recent runs provider test backup restore retention cleanup preview",
    body: [
      {type: "p", text: "The Usage page shows recent and total token use. This can help you see how heavily an agent is being used and whether changes such as Function Groups are reducing the amount of repeated input sent to the model."},
      {type: "list", items: ["Today, month and lifetime totals show overall usage.","Recent runs show individual completed requests, including request counts, how long they took and whether they succeeded or failed.","Cached input is a reusable part of the input included within the total token count. Some providers charge less for these cached tokens.","Retention settings control how long detailed usage records are kept. This is separate from the lifetime totals."]},
      {type: "heading", text: "If something is not working"},
      {type: "steps", items: ["If the agent cannot answer at all, run the provider connection test. It sends only a minimal test request and does not run Home Assistant actions.","If the answer suggests the model is receiving the wrong instructions, Home Assistant context or tools, use Preview effective request.","Check the recent usage and run information for failed requests or unusual behaviour.","If the problem only affects one feature, check its own page: memory, Knowledge, Functions, Guest Mode or conversation history.","Before making major changes, create a full backup if you want an easy way to restore the agent's saved data."]},
      {type: "note", title: "Configuration export and full backup are different", text: "A configuration export is mainly for copying an agent's behaviour and settings. Full Backup & Restore also includes saved data such as memories, Knowledge sources, retained conversations, the Guest Mode schedule and usage history."},
    ],
    action: {label: "Open diagnostics", page: "usage-maintenance", section: "diagnostics"},
  },
  {
    id: "request-debugging",
    title: "Request debugging: see what was sent",
    summary: "Inspect a real recent provider request when an answer, tool call, or provider error is difficult to explain.",
    body: [
      {type: "p", text: "Request debugging records recent real requests so you can inspect the prompt, context, tools and request settings that were actually sent. Use it when Preview effective request is not enough to explain a real result."},
      {type: "note", title: "Treat captured requests as private", text: "A captured request can include conversation text and Home Assistant context. Use it for targeted troubleshooting and keep the retention period no longer than you need."},
    ],
    action: {label: "Open request debugging", page: "usage-maintenance", section: "request-debugging"},
    terms: "request debugging inspect provider request prompt context tools parameters troubleshooting what was sent diagnostics",
    searchTermsOnly: true,
  },
  {
    id: "backup-restore",
    title: "Backup & Restore",
    summary: "Create a private recovery or migration backup containing an agent's settings and retained Extended OpenAI data.",
    body: [
      {type: "p", text: "A full backup can include the agent configuration, Request Rules, memories, Knowledge sources, archived conversations, Guest Mode schedule and usage data. Provider credentials and temporary runtime state are not included."},
      {type: "p", text: "Restore checks the backup before replacing the current saved agent data. If saving the restored state fails, Extended OpenAI attempts to put the previous data back rather than intentionally leaving only part of the backup applied."},
      {type: "note", title: "Backup files can contain private data", text: "Treat full backups as private even though provider API credentials are excluded."},
    ],
    action: {label: "Open Backup & Restore", page: "usage-maintenance", section: "backup-restore"},
    terms: "backup restore recovery migrate agent memories knowledge archive usage private backup rollback",
    searchTermsOnly: true,
  },
];

export const MEMORY_COMPARISON = [
  ["Conversation context","Natural follow-up questions during an ongoing discussion","Until the Home Assistant session ends or the configured continuity timeout causes a new conversation to start","Carried into the relevant follow-up conversation"],
  ["Temporary memory","Facts that are useful only for a limited time","Until the memory's expiry time","Available while it is still active when relevant to the request"],
  ["Persistent memory","Stable facts and preferences that are worth reusing later","Until you change or delete them","Relevant memories can be selected when a conversation starts or retrieved when needed"],
  ["Conversation archive","Reviewing or searching previous discussions","For the archive retention period you have configured","Previous conversations are searched only when archive access or archive search is used"],
  ["Knowledge Library","Larger reference material such as manuals, policies or project notes","Until you delete the source","Searched when needed, with only the relevant source content retrieved"],
];
